# Generated by Django 3.0.7 on 2020-09-10 13:01

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duname', models.CharField(max_length=25)),
                ('pfname', models.CharField(max_length=25)),
                ('plname', models.CharField(max_length=25)),
                ('pemail', models.EmailField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pstate', models.CharField(max_length=50)),
                ('pcity', models.CharField(max_length=50)),
                ('ppincode', models.IntegerField(default=0)),
                ('pphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('history', models.TextField(max_length=255)),
                ('paddress', models.TextField(max_length=255)),
            ],
        ),
    ]
